language: java
jdk:
    - oraclejdk8

after_success:
- ./gradlew jacocoTestReport coveralls

notifications:
  email:
    recipients:
      - wuyichen24@gmail.com
    on_success: never
    on_failure: always
